### ISSUE TITLE
Bat file is detected with "alien" for win defender

### ISSUE THREAD

**Issue by skibidisigmareal** [C5Hackr/Phantom#10]
![image](https://github.com/C5Hackr/Phantom/assets/146603142/debd20fe-c822-46f5-8020-ef17067c785d)

basically js all i need im js looking for a fix for win defender

**Comment by C5Hackr** [comment]
This is not a "issue", please do not open requests related to detection issues, if you want to make a pull request and contribute to the project that is fine, but I will no longer be updating this repo unless it relates to a programmatical bug.
