### ISSUE TITLE
Powershell Load area has an issue

### ISSUE THREAD

**Issue by unblockedgames2** [C5Hackr/Phantom#11]
u just cant use it, it will build but the bat will give an error

**Comment by C5Hackr** [comment]
Incomplete report with little to no information or steps to reproduce the issue, closed.

**Comment by unblockedgames2** [comment]
New-Object : Exception calling ".ctor" with "1" argument(s): "Buffer cannot be null.
Parameter name: buffer"
At line:1 char:675
+ ... m_var){ $PPsPG=New-Object System.IO.MemoryStream(,$param_var); $RANBp ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : Exception calling ".ctor" with "2" argument(s): "Value cannot be null.
Parameter name: stream"
At line:1 char:772
+ ... eam; $BCiNp=New-Object System.IO.Compression.GZipStream($PPsPG, [IO.C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At line:1 char:871
+ ... pression.CompressionMode]::Decompress); $BCiNp.CopyTo($RANBp); $BCiNp ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:1 char:894
+ ... onMode]::Decompress); $BCiNp.CopyTo($RANBp); $BCiNp.Dispose(); $PPsPG ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:1 char:912
+ ... s); $BCiNp.CopyTo($RANBp); $BCiNp.Dispose(); $PPsPG.Dispose(); $RANBp ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Load" with "1" argument(s): "Array cannot be null."
At line:1 char:1017
+ ... aram2_var){ $qzkUr=[System.Reflection.Assembly]::('daoL'[-1..-4] -joi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

You cannot call a method on a null-valued expression.
At line:1 char:1127
+ ... ; $GdQZu=$qzkUr.EntryPoint; $GdQZu.Invoke($null, $param2_var);}$host. ...
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Load" with "1" argument(s): "Could not load file or assembly '195072 bytes loaded from Anonymously
Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An
attempt was made to load a program with an incorrect format."
At line:1 char:1017
+ ... aram2_var){ $qzkUr=[System.Reflection.Assembly]::('daoL'[-1..-4] -joi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException

You cannot call a method on a null-valued expression.
At line:1 char:1127
+ ... ; $GdQZu=$qzkUr.EntryPoint; $GdQZu.Invoke($null, $param2_var);}$host. ...
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull


C:\Users\Fanta\Deskop

**Comment by unblockedgames2** [comment]
does this help
