### ISSUE TITLE
Trojan:MSIL/Heracles.KAO!MTB detected when ran without windows defender on

### ISSUE THREAD

**Issue by skibidisigmareal** [C5Hackr/Phantom#7]
It says Affected Items: amsi: \Device\HarddiskVolume3\Windows\System32\WindowsPowerShell\v1.0\powershell.exe. Since the program uses powershell so it can obf it, it is flagging powershell. It can't actually delete powershell, and the file is undetected, it's not much of an issue however, when u run the file, it will get flagged immediately putting suspicion on the file. Any fix? 
![image](https://github.com/C5Hackr/Phantom/assets/146603142/e2704d0e-bc5d-45e4-95b4-960f36426c20)

**Comment by Knakiri** [comment]
womp womp

**Comment by skibidisigmareal** [comment]
LMAO

**Comment by C5Hackr** [comment]
This is a runtime detection, and can be fixed by verifying that the amsi addresses are still correct and by changing the string obfuscation for the strings "amsi.dll" and "AmsiScanBuffer".
