### ISSUE TITLE
Can you provide more information on how you would fix the powershell runtime detection?

### ISSUE THREAD

**Issue by skibidisigmareal** [C5Hackr/Phantom#8]
This is a runtime detection, and can be fixed by verifying that the amsi addresses are still correct and by changing the string obfuscation for the strings "amsi.dll" and "AmsiScanBuffer".

_Originally posted by @C5Hackr in https://github.com/C5Hackr/Phantom/issues/7#issuecomment-2180099295_

**Comment by C5Hackr** [comment]
For finding the addresses for AmsiScanBuffer you can switch it to use GetProcAddress or use the pdf guide on this repo to find out how to manually get the addresses, and as for the "AmsiScanBuffer" string replace the "*" character with a bigger string of unique text.
